import type { LifecycleStage } from '@life-as-code/validators'

export type FieldTier = 'required' | 'standard' | 'extended'

export interface FieldConfig {
  key: string
  label: string
  guidedPrompt: string
  guidedHint?: string
  placeholder?: string
  tier: FieldTier
}

export const STAGE_FIELD_CONFIGS: Record<LifecycleStage, FieldConfig[]> = {
  problem: [
    {
      key: 'problemStatement',
      label: 'Problem Statement',
      guidedPrompt: 'What human problem triggered this feature?',
      guidedHint: 'Describe it as a user experience, not a technical issue. What are they unable to do, or what friction do they face?',
      placeholder: 'e.g. Users on mobile can\'t filter results by date, so they scroll through hundreds of irrelevant entries.',
      tier: 'required',
    },
    {
      key: 'impactedUsers',
      label: 'Impacted Users',
      guidedPrompt: 'Who experiences this problem, and how often?',
      guidedHint: 'Think about which user roles, how many people, and how frequently they hit this.',
      placeholder: 'e.g. ~40% of users access on mobile. This happens every time they search.',
      tier: 'standard',
    },
    {
      key: 'successMetric',
      label: 'Success Metric',
      guidedPrompt: 'How will you know when this problem is solved?',
      guidedHint: 'A good metric is observable and specific — not "users are happy" but "support tickets for X drop by 50%".',
      placeholder: 'e.g. Filter usage rate on mobile increases to match desktop (currently 8% vs 62%).',
      tier: 'standard',
    },
    {
      key: 'priorityRationale',
      label: 'Priority Rationale',
      guidedPrompt: 'Why is this the right time to solve it?',
      guidedHint: 'What business event, user signal, or opportunity makes this urgent now?',
      placeholder: 'e.g. Mobile traffic grew 80% last quarter and is now majority of sessions.',
      tier: 'extended',
    },
  ],
  analysis: [
    {
      key: 'analysisNotes',
      label: 'Analysis Notes',
      guidedPrompt: 'What analysis or research supports this solution?',
      guidedHint: 'What did you investigate? What did you find? What should this feature NOT do?',
      placeholder: 'e.g. Root cause is the filter component using position:relative — breaks at <768px. Redesign needed.',
      tier: 'required',
    },
    {
      key: 'dataPoints',
      label: 'Supporting Data',
      guidedPrompt: 'What data or evidence backs up the need for this?',
      guidedHint: 'Numbers, quotes from user research, support ticket volume — anything concrete.',
      placeholder: 'e.g. 23 support tickets in the last 30 days specifically about mobile filtering.',
      tier: 'standard',
    },
    {
      key: 'riskFactors',
      label: 'Risk Factors',
      guidedPrompt: 'What risks could come with solving this?',
      guidedHint: 'Technical debt introduced, edge cases in the solution, performance concerns, dependency risks.',
      placeholder: 'e.g. Refactoring FilterDrawer may affect desktop layout — needs regression testing.',
      tier: 'standard',
    },
    {
      key: 'competitorAnalysis',
      label: 'Competitor Analysis',
      guidedPrompt: 'How do others or competitors handle this problem?',
      guidedHint: 'Not required — only fill this if competitive context shapes your decision.',
      placeholder: 'e.g. Competitor uses a bottom sheet on mobile. We\'ll use a slide-in drawer instead.',
      tier: 'extended',
    },
  ],
  requirements: [
    {
      key: 'requirementsList',
      label: 'Requirements',
      guidedPrompt: 'What must this feature do?',
      guidedHint: 'List discrete behaviours the feature must have. Each requirement should be independently testable.',
      placeholder: 'Add a requirement...',
      tier: 'required',
    },
    {
      key: 'outOfScope',
      label: 'Out of Scope',
      guidedPrompt: 'What should this feature explicitly NOT do?',
      guidedHint: 'Defining boundaries prevents scope creep. What might someone expect but should be in a future feature?',
      placeholder: 'e.g. Saved filters are out of scope — that\'s a separate personalisation story.',
      tier: 'standard',
    },
    {
      key: 'constraints',
      label: 'Constraints',
      guidedPrompt: 'What constraints shape the solution?',
      guidedHint: 'Technical limits, time limits, regulatory requirements, third-party API limitations.',
      placeholder: 'e.g. Must work without JS (progressive enhancement). No new third-party dependencies.',
      tier: 'standard',
    },
    {
      key: 'edgeCases',
      label: 'Edge Cases',
      guidedPrompt: 'What edge cases must be handled?',
      guidedHint: 'Think about empty states, error states, extreme inputs, and unusual user paths.',
      placeholder: 'e.g. If no results match the filter — show "No results" not a broken layout.',
      tier: 'extended',
    },
  ],
  design: [
    {
      key: 'designNotes',
      label: 'Design Notes',
      guidedPrompt: 'How should this feature work and feel?',
      guidedHint: 'Describe the interaction and visual approach. You don\'t need a Figma link — words are enough.',
      placeholder: 'e.g. A slide-in drawer from the right, triggered by a "Filter" button fixed to the bottom-right on mobile.',
      tier: 'required',
    },
    {
      key: 'uxConsiderations',
      label: 'UX Considerations',
      guidedPrompt: 'What UX patterns or interactions matter here?',
      guidedHint: 'Focus on moments of friction: what happens on tap, scroll, loading, error, or empty state.',
      placeholder: 'e.g. Drawer should close on backdrop tap. Active filters persist through drawer close/reopen.',
      tier: 'standard',
    },
    {
      key: 'alternatives',
      label: 'Alternatives Considered',
      guidedPrompt: 'What other approaches did you consider, and why did you choose this one?',
      guidedHint: 'A quick note here helps future readers understand why the design is the way it is.',
      placeholder: 'e.g. Considered a top sheet but it conflicted with the sticky header. Drawer wins.',
      tier: 'standard',
    },
    {
      key: 'accessibilityNotes',
      label: 'Accessibility Notes',
      guidedPrompt: 'What accessibility requirements apply to this feature?',
      guidedHint: 'Focus management, keyboard navigation, ARIA roles, screen reader behaviour.',
      placeholder: 'e.g. Drawer must trap focus. Esc closes. Filter state announced via aria-live.',
      tier: 'extended',
    },
  ],
  implementation: [
    {
      key: 'implementationNotes',
      label: 'Implementation Notes',
      guidedPrompt: 'How will this be built technically?',
      guidedHint: 'High-level approach — which files change, what patterns are used, how data flows.',
      placeholder: 'e.g. New FilterDrawer component using position:fixed. Filter state lifted to URL params via useSearchParams.',
      tier: 'required',
    },
    {
      key: 'technicalStack',
      label: 'Technical Choices',
      guidedPrompt: 'Which libraries, patterns, or frameworks will you use?',
      guidedHint: 'Only list choices that need justification or are non-obvious. Skip boilerplate.',
      placeholder: 'e.g. Using Radix Dialog for the drawer (already in codebase). No new deps.',
      tier: 'standard',
    },
    {
      key: 'dependencies',
      label: 'Dependencies',
      guidedPrompt: 'What does this depend on — other code, services, or teams?',
      guidedHint: 'Blockers, shared infrastructure, API contracts with other teams, external services.',
      placeholder: 'e.g. Depends on Search API returning filterable fields. API team confirmed this is available.',
      tier: 'standard',
    },
    {
      key: 'performanceNotes',
      label: 'Performance Notes',
      guidedPrompt: 'Are there any performance targets or bottlenecks to watch?',
      guidedHint: 'Render budget, bundle size impact, slow queries, cache invalidation concerns.',
      placeholder: 'e.g. Filter re-query must complete in <300ms. Will debounce input at 200ms.',
      tier: 'extended',
    },
  ],
  validation: [
    {
      key: 'validationNotes',
      label: 'Validation Plan',
      guidedPrompt: 'How will this feature be tested before shipping?',
      guidedHint: 'Manual testing steps, automated test approach, what "done" looks like from a QA perspective.',
      placeholder: 'e.g. Manual test on iOS Safari and Android Chrome. Playwright test covering filter combinations.',
      tier: 'required',
    },
    {
      key: 'testCases',
      label: 'Test Cases',
      guidedPrompt: 'What are the key scenarios that must pass?',
      guidedHint: 'List the most important happy paths, edge cases, and failure cases to cover.',
      placeholder: 'e.g. 1. Filter by single category. 2. Filter by date + category. 3. No results state.',
      tier: 'standard',
    },
    {
      key: 'testEnvironment',
      label: 'Test Environment',
      guidedPrompt: 'What environment or data setup do you need to test this?',
      guidedHint: 'Seed data requirements, feature flags, staging configuration, device requirements.',
      placeholder: 'e.g. Need >50 test items across categories in staging. Feature flag: mobile-filter-v1.',
      tier: 'standard',
    },
    {
      key: 'loadTestingNotes',
      label: 'Load Testing',
      guidedPrompt: 'Does this need load or performance testing?',
      guidedHint: 'Only fill this if the feature affects high-traffic endpoints or has performance SLAs.',
      placeholder: 'e.g. Filter endpoint must handle 500 concurrent requests at <200ms p99.',
      tier: 'extended',
    },
  ],
  documentation: [
    {
      key: 'documentationNotes',
      label: 'Documentation Plan',
      guidedPrompt: 'What documentation does this feature need?',
      guidedHint: 'User-facing docs, internal dev notes, API docs, changelog entry — whatever applies.',
      placeholder: 'e.g. Update help centre article on filtering. Add component README for FilterDrawer.',
      tier: 'required',
    },
    {
      key: 'audience',
      label: 'Target Audience',
      guidedPrompt: 'Who will read this documentation?',
      guidedHint: 'Different audiences need different detail levels. Knowing the audience shapes the writing.',
      placeholder: 'e.g. End users (help centre) and internal engineers (component README).',
      tier: 'standard',
    },
    {
      key: 'docFormat',
      label: 'Format & Location',
      guidedPrompt: 'Where will the docs live, and in what format?',
      guidedHint: 'Notion page, GitHub wiki, in-repo markdown, help centre CMS — be specific.',
      placeholder: 'e.g. Help centre CMS (Intercom) + `/docs/components/filter-drawer.md` in repo.',
      tier: 'standard',
    },
    {
      key: 'translationNotes',
      label: 'i18n / Translation',
      guidedPrompt: 'Any internationalisation or translation considerations?',
      guidedHint: 'New string keys, RTL layout, locale-specific formatting, translation team handoff.',
      placeholder: 'e.g. 3 new i18n keys. RTL layout tested in Arabic locale.',
      tier: 'extended',
    },
  ],
  delivery: [
    {
      key: 'deliveryPlan',
      label: 'Delivery Plan',
      guidedPrompt: 'What is the plan to ship this feature?',
      guidedHint: 'Who deploys it, when, to which environment, and what the sign-off criteria are.',
      placeholder: 'e.g. Ship to staging Monday. Sign-off from PM on mobile devices. Prod deploy Wednesday.',
      tier: 'required',
    },
    {
      key: 'rolloutStrategy',
      label: 'Rollout Strategy',
      guidedPrompt: 'Will this go to all users at once, or roll out in stages?',
      guidedHint: 'Feature flags, percentage rollouts, beta groups, geographic phases.',
      placeholder: 'e.g. Feature flagged behind mobile-filter-v1. 10% → 50% → 100% over 3 days.',
      tier: 'standard',
    },
    {
      key: 'rollbackPlan',
      label: 'Rollback Plan',
      guidedPrompt: 'If something breaks after shipping, how do you roll back?',
      guidedHint: 'The simpler the rollback, the safer the deploy. Flag off? Revert commit? DB migration?',
      placeholder: 'e.g. Toggle feature flag off. No DB changes — rollback is instant.',
      tier: 'standard',
    },
    {
      key: 'monitoringPlan',
      label: 'Post-Delivery Monitoring',
      guidedPrompt: 'What will you monitor after launch?',
      guidedHint: 'Error rates, key metrics, dashboards to watch, alert thresholds.',
      placeholder: 'e.g. Monitor filter error rate in Datadog for 48h. Alert if >1% of filter requests fail.',
      tier: 'extended',
    },
  ],
  support: [
    {
      key: 'supportNotes',
      label: 'Support Notes',
      guidedPrompt: 'What support considerations come with this feature?',
      guidedHint: 'What might users ask about? What should support agents know? What are the gotchas?',
      placeholder: 'e.g. Users may report filters "resetting" — this is expected on browser back. Documented in help centre.',
      tier: 'required',
    },
    {
      key: 'knownIssues',
      label: 'Known Issues',
      guidedPrompt: 'Are there any known limitations or issues to communicate at launch?',
      guidedHint: 'Be honest. Known issues documented here prevent future confusion.',
      placeholder: 'e.g. Filter state is not preserved across sessions (coming in v2).',
      tier: 'standard',
    },
    {
      key: 'escalationPath',
      label: 'Escalation Path',
      guidedPrompt: 'How should issues with this feature be escalated?',
      guidedHint: 'Who owns this feature? Slack channel, on-call rotation, Jira board.',
      placeholder: 'e.g. #mobile-squad Slack. PagerDuty rotation: mobile-infra.',
      tier: 'standard',
    },
    {
      key: 'slaDefinitions',
      label: 'SLA Definitions',
      guidedPrompt: 'Are there any SLA or response-time commitments for this feature?',
      guidedHint: 'Only fill this if there are contractual or explicit SLAs. Skip otherwise.',
      placeholder: 'e.g. Filter results must return within 500ms per enterprise SLA.',
      tier: 'extended',
    },
  ],
}
