export const EventType = {
  FEATURE_CREATED: 'FEATURE_CREATED',
  FEATURE_UPDATED: 'FEATURE_UPDATED',
  FEATURE_FROZEN: 'FEATURE_FROZEN',
  FEATURE_SPAWNED: 'FEATURE_SPAWNED',
  STAGE_UPDATED: 'STAGE_UPDATED',
  ANNOTATION_ADDED: 'ANNOTATION_ADDED',
  SCHEMA_UPDATED: 'SCHEMA_UPDATED',
} as const

export type EventTypeValue = (typeof EventType)[keyof typeof EventType]
